[package]
name = "holofuel_init"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
holochain_types = "0.1.0"
tokio = { version = "1.11", features = [ "full" ] }
serde = { version = "1.0", features = ["derive"] }
holofuel_connect = { path = "../holofuel_connect" }